### ISSUE TITLE
Record auto-numbering + Data Access Groups = incorrect hyperlinks

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-instance-table#1]
When using record auto-numbering & DAGs, the record ID in the hyperlinks is incorrect because the record ID is interpreted as a calculation
For example, record ID 1-3 yields hyperlinks with "...&id=-2&..."

**Comment by lsgs** [comment]
Thanks for reporting this @steentje34. I've committed a fix and will do a new release to the REDCap repo.
