### ISSUE TITLE
Display label of ontology instead of raw value

### ISSUE THREAD

**Issue by CourtHill235** [lsgs/redcap-instance-table#10]
Love having this external module in our project! However, I have noticed a bug with the instance table and an ontology field.

In our project the variable [units] has an bioportal onotolgy on the field. Both the onotology label and raw value show in our repeating form and the report, but only the raw value shows in the instance table. See screenshot below.
![pic 1](https://user-images.githubusercontent.com/58669543/70396864-e89ce380-1a60-11ea-882f-0a1974c51169.png)
![pic 2](https://user-images.githubusercontent.com/58669543/70396865-e9ce1080-1a60-11ea-83ec-6948308926be.png)
![pic 3](https://user-images.githubusercontent.com/58669543/70396866-eaff3d80-1a60-11ea-9e77-d1dcbe0d9061.png)

**Comment by lsgs** [comment]
This is fixed in release 1.2.0 @CourtHill235. You should now get the label as well as the value, just like with other categorical fields.
