### ISSUE TITLE
Permissions Not Working Correctly

### ISSUE THREAD

**Issue by Eduardoxgg** [lsgs/redcap-instance-table#11]
We're on REDCap version 9.1.3 and Instance Table 1.1.1.

When users have read-only access to an instrument, that instrument's data does not show up in Instance Tables. I have to mark View and Edit for that instrument for users to have rights to see any data in Instance Tables.

**Comment by lsgs** [comment]
This is fixed in release v1.2.0. You should now get the data displayed in the table when the user's permissions for the repeating form are "read only". There will be no "Add New" button.
