### ISSUE TITLE
Crash with PHP8

### ISSUE THREAD

**Issue by teigentler** [lsgs/redcap-instance-table#17]
I experienced an issue when updating to PHP8. In some circumstances the JSON file seems to be corrupted.  The JSON file looks like

```
<div class="red" style="margin:20px 0px;max-width:700px;">
<b>REDCap crashed due to an unexpected PHP fatal error!</b><br><br>
<b>Error message:</b> Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, array given in /var/www/html/redcap/modules/instance_table_v1.3.0/InstanceTable.php:319
Stack trace:
#0 /var/www/html/redcap/modules/instance_table_v1.3.0/InstanceTable.php(319): trim()
#1 /var/www/html/redcap/modules/instance_table_v1.3.0/instance_table_ajax.php(9): MCRI\InstanceTable\InstanceTable-&gt;getInstanceData()
#2 /var/www/html/redcap/redcap_v10.8.1/ExternalModules/index.php(123): require_once('...')
#3 {main}
  thrown<br>
<b>File:</b> /var/www/html/redcap/modules/instance_table_v1.3.0/InstanceTable.php<br>
<b>Line:</b> 319<br>
</div>
```
Regards
Thomas

**Comment by lsgs** [comment]
Thanks for the report @teigentler. InstanceTable(319) is 
```
if (trim($value)==='') {
```
and if `$value` there is an array it'll be because there's a checkbox field. Are you able to confirm that you only see this crash when there's a checkbox field on the repeating form?

I don't have PHP8 yet but I reckon including a check on the type in the condition will fix it:
```
if (is_string($value) && trim($value)==='') {
```

**Comment by teigentler** [comment]
I have two similar forms, and indeed the one which is not working has checkboxes included where the other has not.

**Comment by lsgs** [comment]
I've committed this fix and it will be in the next release.
