### ISSUE TITLE
Display instance table incorrectly when viewing as a survey

### ISSUE THREAD

**Issue by iris-y-l** [lsgs/redcap-instance-table#19]
Hi Luke,
The instance table displays incorrectly (few gone missing) when viewing as a survey. Please see below image, descriptive field for each table section I have branching logic applied, not sure if this cause the issue.
![image](https://user-images.githubusercontent.com/79240395/132463658-25616b2a-0e4f-4e25-8595-dfc56746460c.png)
![image](https://user-images.githubusercontent.com/79240395/132463838-4f5275cd-9ba6-42b2-acdb-54545a6a953e.png)

Let me know if there is any further information required.
Thanks for the help!

Warm regards,
Iris

**Comment by iris-y-l** [comment]
The display problem only occurs if the instance table (in survey view) try to display data of repeating surveys but one of them has not data in there. It seems it's not branching logic that caused the problem
![image](https://user-images.githubusercontent.com/79240395/133031206-1497848c-eaae-4724-8ff0-a5d5fba0acde.png)
![image](https://user-images.githubusercontent.com/79240395/133032342-0ba4cc27-360b-4af9-82a0-601f66df4ed2.png)
![image](https://user-images.githubusercontent.com/79240395/133032375-15c43794-376d-49c5-9bd7-54588774a8f2.png)

**Comment by lsgs** [comment]
Thanks for the report @iris-y-l. This will be fixed in the new release.
