### ISSUE TITLE
New instance number incorrect when clicking 'Add new'

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-instance-table#2]
It seems that currently, when  'Add new' is clicked, the new instance number is based on the number of instance present. For example, if 25 instances are already present, the new instance number will be 26.

However, this leads to problems when instances of a repeating form are deleted. In my example, 26 instances were once present, but an in-between instance has been deleted. If 'Add new' is clicked', instance number 26 is assumed, which is in fact the last completed instance.

Could the max instance number + 1 be used instead of counting the number of instances present?

**Comment by lsgs** [comment]
Arrgh - I thought I'd fixed this before! Thanks for reporting @steentje34 - it is now fixed and I'll do a new release.
