### ISSUE TITLE
@INSTANCETABLE_REF does not default to current visit instance in pop-up.

### ISSUE THREAD

**Issue by slkrislov** [lsgs/redcap-instance-table#20]
Using the @INSTANCETABLE_REF action tag to link two repeating forms, the reference field does not default to the instance number from the repeating form that the instance table is on.  The URL for the data entry form in the pop-up contains "&parent_instance=[appropriate instance number]" at the end but not any indication for the default value for the reference field.   

I also tried using the legacy @INSTANCETABLE_SRC and @INSTANCETABLE_DST tags and those did not work either.

**Comment by lsgs** [comment]
I have submitted a new version with various updates and I believe this is fixed. The @INSTANCETABLE_REF functionality is functioning OK in my test project.
