### ISSUE TITLE
"Uncaught TypeError: i is null" when instance data is null

### ISSUE THREAD

**Issue by tertek** [lsgs/redcap-instance-table#21]
There is a Javascript error caused by DataTables when instance data is `Null`. 

![image](https://user-images.githubusercontent.com/75415872/150826156-b70025a3-118f-4413-9026-1274fa70bd52.png)

Reason: `Null` is not valid JSON .

Solution: Return empty array within instance_table_ajax.php:

```php
//  instance_table_ajax.php:9

$instanceData =  $module->getInstanceData($_GET['record'], $_GET['event_id'], $_GET['form_name'], $_GET['filter']);
$data= [];

if( $instanceData != NULL ) {
    $data= $instanceData;
}
echo json_encode(array('data' =>$data));
```

I noticed this during a run of automated tests with cypress which where blocked by this error.

**Comment by lsgs** [comment]
Thanks for reporting this @tertek. Can you say how you managed to get a null value returned by the `getInstanceData()` method? It should always return an array - and an empty one when there are no instances to display.

Could it be that you are using PHP 8 and the instance data to be displayed contained a checkbox field? That is about to be fixed - see https://github.com/lsgs/redcap-instance-table/issues/24

**Comment by lsgs** [comment]
New version submitted with this issue fixed.

**Comment by tertek** [comment]
@lsgs thank you for catching uo on this. I had forgot!
