### ISSUE TITLE
TypeError: array_keys() - when no data in repeating form/event

### ISSUE THREAD

**Issue by Nick-MRINZ** [lsgs/redcap-instance-table#25]
Hi Luke, 

We are using the instance table module v1.4.0 with the following server configuration: REDCap 12.4.6 · PHP 8.0.0 (Windows OS) · MySQL 8.0.27.  Currently I am getting an error every time a user uses an instance table that does not have any data in the associated repeating form/event already. 

**Error:**
The 'instance_table' module threw the following exception when calling the hook method 'redcap_every_page_before_render':
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in C:\inetpub\wwwroot\redcap\modules\instance_table_v1.4.0\InstanceTable.php:795

**Fix:**
I have fixed the issue by making the following code change on line 795-800 of InstanceTable.php.

```php
if($recordData[$_GET['id']]['repeat_instances'][$_GET['event_id']][$formKey] == null){
 $_GET['instance'] = 1;
} else {
 $currentInstances = array_keys($recordData[$_GET['id']]['repeat_instances'][$_GET['event_id']][$formKey]);
 $_GET['instance'] = 1 + end($currentInstances);
}
```
Cheers,
Nick

**Comment by lsgs** [comment]
Thanks for reporting Nick. I've submitted a new version with various updates, including the following change for this issue:

Previous:
`$_GET['instance'] = 1 + end($currentInstances);`

New:
`$_GET['instance'] = (is_null($currentInstances)) ? 1 : 1 + end($currentInstances);`

**Comment by Nick-MRINZ** [comment]
Awesome thanks Luke!
