### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by robinfitz26** [lsgs/redcap-instance-table#26]
Hi Luke - @lsgs  and everyone- We have installed and enabled the Instance Table external module in REDCap 12.4.12. It is functioning on the application side and doing what it is designed to do, but our back end analyst is seeing several exceptions for which he is concerned. Please see the attached .eml files (converted to txt).

Any feedback appreciated.

Thanks,
[REDCap External Module Hook Exception - instance_table [1].txt](https://github.com/lsgs/redcap-instance-table/files/9932255/REDCap.External.Module.Hook.Exception.-.instance_table.1.txt)

[REDCap External Module Hook Exception - instance_table [2].txt](https://github.com/lsgs/redcap-instance-table/files/9932256/REDCap.External.Module.Hook.Exception.-.instance_table.2.txt)

[REDCap External Module Hook Exception - instance_table.txt](https://github.com/lsgs/redcap-instance-table/files/9932257/REDCap.External.Module.Hook.Exception.-.instance_table.txt)

Robin Fitzpatrick

**Comment by krobertson71** [comment]
Just filling in the blanks.  he downloaded the latest 1.5.5 and we are running
REDCap 12.4.12 · PHP 8.0.13 (Linux/Unix OS) · MySQL 8.0.28.

The error seems to be similar to the one before this one but not quite as this fix/update should have fixed it.

**Comment by lsgs** [comment]
Thanks for posting the exception messages @robinfitz26, and for the confirmation @krobertson71. I have put out a fix so look out for v1.5.6 in the repo soon.
