### ISSUE TITLE
1.5.6 still throwing exceptions

### ISSUE THREAD

**Issue by krobertson71** [lsgs/redcap-instance-table#27]
Still getting this after upgrading to 1.5.6

[This message was automatically generated by REDCap]

The 'instance_table' module threw the following exception when calling the hook method 'redcap_every_page_before_render':

TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/redcap/modules/instance_table_v1.5.6/InstanceTable.php:822
Stack trace:
#0 /var/www/html/redcap/modules/instance_table_v1.5.6/InstanceTable.php(822): array_key_exists()
#1 /var/www/html/redcap/redcap_v12.4.12/ExternalModules/classes/ExternalModules.php(3230): MCRI\InstanceTable\InstanceTable->redcap_every_page_before_render()
#2 /var/www/html/redcap/redcap_v12.4.12/ExternalModules/classes/ExternalModules.php(3375): ExternalModules\ExternalModules::startHook()
#3 /var/www/html/redcap/redcap_v12.4.12/ExternalModules/classes/ExternalModules.php(3408): ExternalModules\ExternalModules::ExternalModules\{closure}()
#4 /var/www/html/redcap/redcap_v12.4.12/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook()
#5 /var/www/html/redcap/redcap_v12.4.12/Classes/System.php(777): Hooks::call()
#6 /var/www/html/redcap/redcap_v12.4.12/Config/init_project.php(7): System::initProjectPage()
#7 /var/www/html/redcap/redcap_v12.4.12/DataEntry/index.php(6): require_once('...')
#8 {main}

**Comment by lsgs** [comment]
Please try release 1.5.7. I accounted for another case...
