### ISSUE TITLE
Feature Request: Hide raw values

### ISSUE THREAD

**Issue by vndmark** [lsgs/redcap-instance-table#29]
Thank you for the amazing work on the module, I just have a request for an additional feature: would it be possible to hide the raw values in the table? As of now the labels are presented with the raw values in brackets () next to them. This confuses some of our users, perhaps in combination with the @INSTANCETABLE=event_name:form_name Actiontag?

See image below:
![REDCap_Instance_table_raw_values](https://user-images.githubusercontent.com/87768811/217253520-83000dc0-bce8-47d2-a00c-2d66aa5a93be.jpg)

Of course, if I find the time I would like to propose a PR.

**Comment by vndmark** [comment]
I saw that in the module you include the raw choices for questions like dropdown, radio, yes/no etc. Would you be open for an option to not add these choices? Maybe with another Actiontag? I make an PR, if you'd like

**Comment by lsgs** [comment]
I've added this to my dev list: `@INSTANCETABLE_HIDECHOICEVALUES`

**Comment by lsgs** [comment]
Implemented in release v1.7.1
