### ISSUE TITLE
Sort table by variable

### ISSUE THREAD

**Issue by Akeem832** [lsgs/redcap-instance-table#3]
It would be nice if you could choose a variable to sort by; e.g. @INSTANCETABLE_SORT_H2L=[variable_x]  or _SORT_L2H  to swith between sorting High to Low or the other way around.

**Comment by lsgs** [comment]
Yes that is a good idea @Akeem832. I'm not sure I'd implement it using an additional action tag though. I think I'd prefer it to be a project-level module configuration option where you can pick the field and also the sort direction (ascending/descending). The other thing that would be good would be for it to remember any user-applied sort.

**Comment by lsgs** [comment]
v1.2.0 now implements the state saving functionality of DataTables e.g. to remember user's page and column sort from previous sessions.
