### ISSUE TITLE
INSTANCETABLE-REF interferinng with [current-instance]

### ISSUE THREAD

**Issue by johnlct** [lsgs/redcap-instance-table#33]
INSTANCETABLE-REF is interfering with smart variable [current-instance] during data piping.

![Screenshot 2023-04-27 130657](https://user-images.githubusercontent.com/13297782/234749966-3f97127e-e60f-44cf-b0f5-9d6e9995403c.png)

The image above shows how this is interfering. The instance at the moment is instance 2 but the pipe data using [current-instance] is fixated to 1.

REDCap community topic: https://redcap.vanderbilt.edu/community/post.php?id=203654

**Comment by lsgs** [comment]
I replied on your Community post @johnlct [https://redcap.vanderbilt.edu/community/post.php?id=203654&comment=205903](https://redcap.vanderbilt.edu/community/post.php?id=203654&comment=205903)
