### ISSUE TITLE
@INSTANCETABLE_SCROLLX not working

### ISSUE THREAD

**Issue by bhaumikism** [lsgs/redcap-instance-table#37]
The horizontal scroll bar is not getting enabled, thus getting that table to grow wide which causes the whole form to grow wide

**Comment by lsgs** [comment]
Please can you confirm that you are using up-to-date versions of REDCap (13.7+) and the module (1.5.12), @bhaumikism? This was an issue that I thought was fixed in the latest version.

**Comment by lsgs** [comment]
Sorry. Didn't mean to close just yet!

**Comment by bhaumikism** [comment]
Thank you for getting back. We are using 1.3 v module. I will ask the system manager to update this. 
Thanks

**Comment by lsgs** [comment]
That should sort it then @bhaumikism. Please raise a new issue if you experience problems with 1.5.12+
