### ISSUE TITLE
filter operators are not the redcap one

### ISSUE THREAD

**Issue by ThomasVermes** [lsgs/redcap-instance-table#38]
Hi Luke,
I've notice that for the filter function the "unequal" operator has to be written like "!=" and it is not recognized if written with the redcap syntax <>.
If it is too cumbersome to fix it, just a note in the documentation would be fine =)

thanks a lot!

**Comment by lsgs** [comment]
You should find this is now fixed in release 1.5.14, @ThomasVermes
