### ISSUE TITLE
Feature request: Allow 'Save and Exit' in pop-up form

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-instance-table#4]
Currently, only 'Save and Stay' is available when adding a new instance. It would be wonderful if 'Save and Exit' could be allowed additionally.

**Comment by lsgs** [comment]
Yes this would be nice but I have not come up with a way to implement it yet!

**Comment by lsgs** [comment]
This is now implemented thanks to contributions from @susanweber
