### ISSUE TITLE
Function makeOntologyDisplay generates fatal error

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-instance-table#41]
When the database name is not 'redcap', a fatal error is generated when executing the function makeOntologyDisplay.
This is due to following line, which explicitly looks for the database named 'redcap', which may or may not exist on the user's database server:
https://github.com/lsgs/redcap-instance-table/blob/cf58704a4334b269261b0d378ab30aab4ed6bc53/InstanceTable.php#L564

**Comment by lsgs** [comment]
Fix via PR incorporated into upcoming release
