### ISSUE TITLE
Error: Call to a member function isRepeatingEvent() on null

### ISSUE THREAD

**Issue by 274188A** [lsgs/redcap-instance-table#45]
Hi Luke, 

I'm seeing this in my PHP error logs (several times) - looks like a null ref exception error.

`REDCap 13.10.0 · PHP 8.2.7 (Windows OS) · MySQL 8.0.34`

>The 'instance_table' module threw the following exception when calling the hook method 'redcap_every_page_before_render':
Error: Call to a member function isRepeatingEvent() on null in D:\redcap_prod\modules\instance_table_v1.5.13\InstanceTable.php:843
Stack trace:
#0 D:\redcap_prod\redcap_v13.9.2\ExternalModules\classes\ExternalModules.php(3152): MCRI\InstanceTable\InstanceTable->redcap_every_page_before_render('...')
#1 D:\redcap_prod\redcap_v13.9.2\ExternalModules\classes\ExternalModules.php(3319): ExternalModules\ExternalModules::startHook('...', '...', Array)
#2 D:\redcap_prod\redcap_v13.9.2\ExternalModules\classes\ExternalModules.php(3352): ExternalModules\ExternalModules::ExternalModules\{closure}('...', '...')
#3 D:\redcap_prod\redcap_v13.9.2\Classes\Hooks.php(41): ExternalModules\ExternalModules::callHook('...', Array)
#4 D:\redcap_prod\redcap_v13.9.2\Classes\System.php(923): Hooks::call('...', Array)
#5 D:\redcap_prod\redcap_v13.9.2\Config\init_project.php(7): System::initPr
[30-Aug-2023 12:32:42 Australia/Perth] Chunked Log Part 2 of 2:
ojectPage()
#6 D:\redcap_prod\redcap_v13.9.2\DataEntry\index.php(6): require_once('...')
#7 {main}

**Comment by pevmtss** [comment]
Hi Luke, I can confirm I am seeing the same thing. I have found that I trigger this whenever I got to the @ACTION TAGS menu in a project that has Instance Table enabled. Seems like a harmless display issue, but wanted to share.

Instance Table - v1.5.14 
REDCap 13.10.1 · PHP 8.0.28 (Linux/Unix OS) · MySQL 8.0.28

**Comment by lsgs** [comment]
Thanks for the reports @274188A and @pevmtss. The next version will contain some additional checking to try and prevernt this occurring.
