### ISSUE TITLE
Feature request: Show the label of Yes - No fields

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-instance-table#5]
Currently, for Yes - No fields only the code (1 or 0) is displayed in the instance table. It would be wonderful if, similarly to radio buttons fields, the label could be displayed as well.

**Comment by lsgs** [comment]
Thanks for the report @steentje34. [Release 1.0.3](https://github.com/lsgs/redcap-instance-table/releases/tag/1.0.3) fixes this and I have submitted it to the REDCap Repo.
