### ISSUE TITLE
Piping of calculated value not working for repeat instances 

### ISSUE THREAD

**Issue by Nick-MRINZ** [lsgs/redcap-instance-table#50]
Hi Luke, we are using version 1.6.1 of the module and have the following REDCao config: REDCap 13.7.24 · PHP 8.0.0 (Windows OS) · MySQL 8.0.27.

Scenario: We have a calculated field on a repeating instrument which calculates the difference between two dates and pipes that value into an alert for the users. 

Issue: We have had a bug crop up (I think trigged by a recent LTS update) where the piping of the calculated value does not work unless you are on the first repeat instance or the repeat you are on has been saved prior. If you access the repeat instance through the normal REDCap UI, the piping functions as normal but if you are using the instance table module you instead get "___" where the calculated value should be.

![image](https://github.com/lsgs/redcap-instance-table/assets/41651987/2af40d41-e0a5-473b-a5ed-90290c90428d)

![image](https://github.com/lsgs/redcap-instance-table/assets/41651987/4437ac4c-285b-4807-a02a-dc90d46463f7)

**Comment by lsgs** [comment]
Is this still an issue for you @Nick-MRINZ. I've tried a couple of times to replicate the problem without any luck (now in v14.8.2)

![image](https://github.com/user-attachments/assets/78fa20dd-55fa-4585-99be-988a8e7a5a75)

**Comment by Nick-MRINZ** [comment]
Nah just checked and it is working as expected.
