### ISSUE TITLE
Reloading main page after closing INSTANCETABLE popup page

### ISSUE THREAD

**Issue by biostatUniBS** [lsgs/redcap-instance-table#57]
Hi @lsgs 

this is not really an issue but I would like to reload the main page after closing the instance table page, in order to evaluate a Dynamic Query (SQL) field (that create a string concatenating all the entries in one field of the instance table for the main instance).

Any idea how to trigger the page reload?

Thx!

**Comment by lsgs** [comment]
I've bumped up against that before too, but it's a tricky one. It'll refresh the table of instance data on closing, but to refresh the main page would be pretty clunky, I reckon. You'd likely get the "unsaved data" popup which the user could accept or dismiss, and if they dismiss then the page does not reload anyway.

**Comment by biostatUniBS** [comment]
@lsgs, would you suggest would be a good way to overcome the issue? My immediate plan is to remove submit buttons and replace (using Shazam) with a button that before submitting reloads the page in order to execute the Sql query and save the results.Any other suggestion is welcomeStefanoInviato da iPhoneIl giorno 30 mag 2024, alle ore 00:24, Luke ***@***.***> ha scritto:﻿
I've bumped up against that before too, but it's a tricky one. It'll refresh the table of instance data on closing, but to refresh the main page would be pretty clunky, I reckon. You'd likely get the "unsaved data" popup which the user could accept or dismiss, and if they dismiss then the page does not reload anyway.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Informativa sulla Privacy: https://www.unibs.it/it/node/1452

**Comment by lsgs** [comment]
Sorry I missed your erply @biostatUniBS. I think your plan was good though - injecting some JavaScript to do that customisation either using Shazam or the JS Injector module.
