### ISSUE TITLE
Bug: New instance number incorrect when clicking 'Add new' to add a second instance

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-instance-table#6]
When adding a new instance in the instance table by clicking 'Add new', a new instance is effectively added. However, when clicking on the 'Add new' button to add a second instance, it opens the first one again. Would it be possible to update the parameters (or at least the instance) in the addNewInstance function when the datatable is refreshed?

**Comment by lsgs** [comment]
Thanks for the report @steentje34. [Release 1.0.3](https://github.com/lsgs/redcap-instance-table/releases/tag/1.0.3) fixes this and I have submitted it to the REDCap Repo.
