### ISSUE TITLE
Feature Request/Bug: hide choices also on instrument

### ISSUE THREAD

**Issue by vi-klaas** [lsgs/redcap-instance-table#63]
The action tag @INSTANCETABLE_HIDECHOICEVALUES supresses the choice field value when the instance table is displayed on a survey.
If the instance table is part of an instrument, not survey, the choice field values are displayed despite the action tag.

From the description, I would expect the action tag to work equally on surveys and instruments.

Just in case this is useful:
REDCap 14.7.4 · PHP 8.1.30 (Windows OS) · MySQL 8.0.11
Instance Table - v1.9.0

**Comment by lsgs** [comment]
This is fixed in release v1.10.0. Thanks for reporting @vi-klaas
