### ISSUE TITLE
@INSTANCETABLE_HIDECHOICEVALUES not working properly

### ISSUE THREAD

**Issue by DOH-NDF1303** [lsgs/redcap-instance-table#64]
We are on REDCap version 14.5.24 and instance table v1.9.0

The action tag "@INSTANCETABLE_HIDECHOICEVALUES" is not working correctly for me, and our REDCap admins have been unable to get it to work. Adding this action tag does not hide the field choice values or make any noticeable change to the instance table.

**Comment by lsgs** [comment]
This issue is fixed in release v1.10.0, @DOH-NDF1303. You just need to grab the updated module version.
