### ISSUE TITLE
Display label of SQL field instead of raw value

### ISSUE THREAD

**Issue by mon-star** [lsgs/redcap-instance-table#8]
Absolutely great external module, we are using it a lot! I just noticed a bug with the instance table and an SQL field. The variable [ip_prescribed] is a dynamic SQL field in my repeating form. In the instance table though, results for [ip_prescribed] only display the raw value and not the label. The SQL field looks as expected on the repeating form (shows the label, not the raw value) and a report page of the repeating form also looks as I would expect. See screenshot below
![image](https://user-images.githubusercontent.com/47546207/65114148-0c83f680-da29-11e9-8164-5d8e213e41a9.png)

**Comment by lsgs** [comment]
This is fixed in release 1.1.1
