### ISSUE TITLE
Long Event Names

### ISSUE THREAD

**Issue by jasonlones** [lsgs/redcap-instance-table#9]
When using two long event names that share characters resulting in a REDCap unique event name ending in a letter (e.g. testing_long_name_arm_1 / ***testing_long_name_arm_1b***), the module displays an error message - 'ERROR: "testing_long_name_arm_1b" is not a repeating form for event "testing long name test1". Contact the project designer.'

**Comment by lsgs** [comment]
v1.2.0 fixes this. It now recognises something like event_name_arm_1b as a valid event name. Thanks for the report @jasonlones.

**Comment by jasonlones** [comment]
Thank you!

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787

Need REDCap help?  Check out remote office hours every Thursday at 2p ET: via WebEx<https://dukemed.webex.com/dukemed/j.php?MTID=m80cefa3357146919ec3fbb4e15cd9ac8>.
